repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8  # Asegúrate de usar una versión correcta y existente
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format